### ISSUE TITLE
Add empty view scenarios after initial onboarding

### ISSUE THREAD

**Issue by dworak** [SUPLA/supla-ios#148]

**Comment by przemyslawzygmunt** [comment]
Please specify what exactly you mean.

**Comment by dworak** [comment]
That's visible shortly after completing the registration flow, without any devices added: ![image](https://user-images.githubusercontent.com/3908338/112143413-1ebf9180-8bd8-11eb-84cb-fd5fa497d0b0.png)

It's widely adopted solution, please check this as an example: https://github.com/dzenbot/DZNEmptyDataSet

**Comment by przemyslawzygmunt** [comment]
That's right. This means you don't have any devices. What should be in this place, according to You ? Instructions on how to add a device? Information "You don't have any devices ...,"

**Comment by mipolansk** [comment]
Looks like duplikate of #173, I'll link it there.
