### ISSUE TITLE
Varilight - Change "Drive" to "Boost"

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-ios#73]

**Comment by mipolansk** [comment]
@przemyslawzygmunt Can you write here a bit more?

**Comment by przemyslawzygmunt** [comment]
<img width="392" alt="Zrzut ekranu 2024-02-24 o 22 34 12" src="https://github.com/SUPLA/supla-ios/assets/6603397/83f4fd0b-76d8-47de-a729-b5bf03fae700">

It's already done.
